# Generated by Django 5.1.2 on 2024-11-07 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=32, verbose_name='Упражнение')),
                ('record', models.IntegerField(verbose_name='Рекорд')),
            ],
            options={
                'verbose_name': 'Рекорд',
                'verbose_name_plural': 'Рекорды',
            },
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ('-id', 'date'), 'verbose_name': ('Статистика',), 'verbose_name_plural': ('Статистика',)},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': ('Тип',), 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterField(
            model_name='statistic',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='homepage.types', verbose_name='Тип'),
        ),
    ]
