# Generated by Django 5.1.2 on 2024-11-07 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_records_alter_statistic_options_alter_types_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 7, 19, 29, 52, 61064), verbose_name='Дата'),
        ),
    ]
